Langkah - langkah :
1. preprocessing drop data yang tidak diperlukan
2. split data sebelum di normalisasikan dan save csv data x.test
3. normalisasi data (min max) data yang telah di preprocessing drop data, save normalisasi (joblib)
4. split data yang telah di normalisasi

In [63]:
import pandas as pd
import numpy as np
data = pd.read_csv('https://raw.githubusercontent.com/AlifnurFathurrahmanPrasodjo/Project-Penambangan-Data/main/b_depressed.csv')
data.fillna(0,inplace=True)
data

,Survey_id,Ville_id,sex,Age,Married,Number_children,education_level,total_members,gained_asset,durable_asset,...,incoming_salary,incoming_own_farm,incoming_business,incoming_no_business,incoming_agricultural,farm_expenses,labor_primary,lasting_investment,no_lasting_investmen,depressed
0,926,91,1,28,1,4,10,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1,747,57,1,23,1,3,8,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,1
2,1190,115,1,22,1,3,9,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
3,1065,97,1,27,1,2,10,4,52667108,19698904,...,0,1,0,1,22288055,18751329,0,7781123,69219765.0,0
4,806,42,0,59,0,4,10,6,82606287,17352654,...,1,0,0,0,53384566,20731006,1,20100562,43419447.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,255,22,1,25,1,1,7,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1425,547,69,1,28,1,4,10,6,15711078,24023054,...,0,1,0,0,23022095,1021536,0,1823477,47384361.0,0
1426,893,184,1,66,0,0,1,1,42440731,22861940,...,0,1,0,0,12545373,10454478,0,46444572,10454478.0,1
1427,363,75,1,51,1,1,12,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1428,231,12,1,33,0,4,8,5,81678391,22861940,...,0,1,0,1,20019212,16682677,0,69642126,13012488.0,0

In [64]:
fd1 = data.drop(data.columns[0:2],axis=1)

fd2 = fd1.drop(fd1.columns[2],axis=1)

fd3 = fd2.drop(fd2.columns[5:10],axis=1)

fd4 = fd3.drop(fd3.columns[6:14],axis=1)


fd1

,sex,Age,Married,Number_children,education_level,total_members,gained_asset,durable_asset,save_asset,living_expenses,...,incoming_salary,incoming_own_farm,incoming_business,incoming_no_business,incoming_agricultural,farm_expenses,labor_primary,lasting_investment,no_lasting_investmen,depressed
0,1,28,1,4,10,5,28912201,22861940,23399979,26692283,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1,1,23,1,3,8,5,28912201,22861940,23399979,26692283,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,1
2,1,22,1,3,9,5,28912201,22861940,23399979,26692283,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
3,1,27,1,2,10,4,52667108,19698904,49647648,397715,...,0,1,0,1,22288055,18751329,0,7781123,69219765.0,0
4,0,59,0,4,10,6,82606287,17352654,23399979,80877619,...,1,0,0,0,53384566,20731006,1,20100562,43419447.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,1,25,1,1,7,5,28912201,22861940,23399979,26692283,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1425,1,28,1,4,10,6,15711078,24023054,15506558,10476722,...,0,1,0,0,23022095,1021536,0,1823477,47384361.0,0
1426,1,66,0,0,1,1,42440731,22861940,22562605,12545372,...,0,1,0,0,12545373,10454478,0,46444572,10454478.0,1
1427,1,51,1,1,12,5,28912201,22861940,23399979,26692283,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1428,1,33,0,4,8,5,81678391,22861940,47855984,10289875,...,0,1,0,1,20019212,16682677,0,69642126,13012488.0,0

In [65]:
fd4.dropna(how="any")



fd4

,sex,Age,Number_children,education_level,total_members,incoming_salary,depressed
0,1,28,4,10,5,0,0
1,1,23,3,8,5,0,1
2,1,22,3,9,5,0,0
3,1,27,2,10,4,0,0
4,0,59,4,10,6,1,0
...,...,...,...,...,...,...,...
1424,1,25,1,7,5,0,0
1425,1,28,4,10,6,0,0
1426,1,66,0,1,1,0,1
1427,1,51,1,12,5,0,0
1428,1,33,4,8,5,0,0

In [66]:
y = fd4['depressed'].values
x = fd4.drop(fd4.columns[6],axis=1)
x

,sex,Age,Number_children,education_level,total_members,incoming_salary
0,1,28,4,10,5,0
1,1,23,3,8,5,0
2,1,22,3,9,5,0
3,1,27,2,10,4,0
4,0,59,4,10,6,1
...,...,...,...,...,...,...
1424,1,25,1,7,5,0
1425,1,28,4,10,6,0
1426,1,66,0,1,1,0
1427,1,51,1,12,5,0
1428,1,33,4,8,5,0

In [67]:
#x.nlargest(3, "Age")
# x.nlargest(3, "Number_children")
#x.nlargest(3, "education_level")
#x.nlargest(3, "total_members")
# x.nlargest(3, "incoming_salary")

#x.nsmallest(3, "Age")
x.nsmallest(3, "Number_children")
#x.nsmallest(3, "education_level")
#x.nsmallest(3, "total_members")
# x.nsmallest(3, "incoming_salary")

    sex  Age  Number_children  education_level  total_members  incoming_salary
10    1   84                0                1              5                0
14    1   56                0               12              2                0
20    1   40                0                7              5                0

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=1)
X_train.shape + X_test.shape

(1143, 6, 286, 6)

In [69]:
X_test

,sex,Age,Number_children,education_level,total_members,incoming_salary
951,1,27,1,11,5,0
1059,1,21,3,10,5,0
1268,0,53,0,14,5,0
236,1,22,4,8,6,1
942,1,30,3,10,5,0
...,...,...,...,...,...,...
1311,1,32,6,10,8,0
1284,0,47,0,1,5,0
602,1,56,0,7,2,0
1319,1,25,2,9,4,0
516,1,61,0,1,5,0

In [70]:
X_train.isna().sum()

sex                0
Age                0
Number_children    0
education_level    0
total_members      0
incoming_salary    0
dtype: int64

In [71]:
from pathlib import Path  
filepath = Path('/content/drive/MyDrive/DATA MINING/TUGAS/model/data_depresi.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
x.to_csv(filepath)

In [72]:
x.isna().sum()

sex                0
Age                0
Number_children    0
education_level    0
total_members      0
incoming_salary    0
dtype: int64

In [73]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [74]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)
y

array([0, 1, 0, ..., 1, 0, 0])

In [75]:
y_class = data['depressed']
y = y_class.values.tolist()
print(y)

[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

In [76]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled = scaler.fit_transform(x)
nama_fitur = x.columns.copy()
scaled_fitur = pd.DataFrame(scaled,columns=nama_fitur)
scaled_fitur

,sex,Age,Number_children,education_level,total_members,incoming_salary
0,1.0,0.148649,0.363636,0.500000,0.363636,0.0
1,1.0,0.081081,0.272727,0.388889,0.363636,0.0
2,1.0,0.067568,0.272727,0.444444,0.363636,0.0
3,1.0,0.135135,0.181818,0.500000,0.272727,0.0
4,0.0,0.567568,0.363636,0.500000,0.454545,1.0
...,...,...,...,...,...,...
1424,1.0,0.108108,0.090909,0.333333,0.363636,0.0
1425,1.0,0.148649,0.363636,0.500000,0.454545,0.0
1426,1.0,0.662162,0.000000,0.000000,0.000000,0.0
1427,1.0,0.459459,0.090909,0.611111,0.363636,0.0
1428,1.0,0.216216,0.363636,0.388889,0.363636,0.0

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(scaled_fitur, y, test_size=0.2, random_state=1)
X_train.shape + X_test.shape

(1143, 6, 286, 6)

In [78]:
import joblib
filename = '/content/drive/MyDrive/DATA MINING/TUGAS/model/norm.sav'
joblib.dump(scaler, filename)

['/content/drive/MyDrive/DATA MINING/TUGAS/model/norm.sav']

In [79]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
probas = clf.predict_proba(X_test)[:,1]
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [80]:
y_class

0       0
1       1
2       0
3       0
4       0
       ..
1424    0
1425    0
1426    1
1427    0
1428    0
Name: depressed, Length: 1429, dtype: int64

In [81]:
X_train.isna().sum()

sex                0
Age                0
Number_children    0
education_level    0
total_members      0
incoming_salary    0
dtype: int64

In [82]:
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
# from sklearn import metrics
# #Try running from k=1 through 30 and record testing accuracy
# k_range = range(1,31)
# scores = {}
# scores_list = []
# for k in k_range:
#         # install model
#         knn = KNeighborsClassifier(n_neighbors=k)
#         knn.fit(X_train,y_train)
      
#         filenameKNN = '/content/drive/MyDrive/DATA MINING/TUGAS/model/knnmodel'+str(k)+'.pkl'
#         joblib.dump(knn,filenameKNN)
#         y_pred=knn.predict(X_test)
#         scores[k] = accuracy_score(y_test,y_pred)
#         scores_list.append(accuracy_score(y_test,y_pred))
# scores

In [83]:
X_test

,sex,Age,Number_children,education_level,total_members,incoming_salary
951,1.0,0.135135,0.090909,0.555556,0.363636,0.0
1059,1.0,0.054054,0.272727,0.500000,0.363636,0.0
1268,0.0,0.486486,0.000000,0.722222,0.363636,0.0
236,1.0,0.067568,0.363636,0.388889,0.454545,1.0
942,1.0,0.175676,0.272727,0.500000,0.363636,0.0
...,...,...,...,...,...,...
1311,1.0,0.202703,0.545455,0.500000,0.636364,0.0
1284,0.0,0.405405,0.000000,0.000000,0.363636,0.0
602,1.0,0.527027,0.000000,0.333333,0.090909,0.0
1319,1.0,0.108108,0.181818,0.444444,0.272727,0.0
516,1.0,0.594595,0.000000,0.000000,0.363636,0.0

In [84]:
import joblib
filenameNB = '/content/drive/MyDrive/DATA MINING/TUGAS/model/modelNB.pkl'
joblib.dump(clf,filenameNB)

['/content/drive/MyDrive/DATA MINING/TUGAS/model/modelNB.pkl']

In [85]:
probas

array([0.09880487, 0.09175213, 0.33151564, 0.1268097 , 0.09271054,
       0.09734194, 0.21744792, 0.52752627, 0.08404968, 0.09818919,
       0.18646244, 0.08978916, 0.15847686, 0.12872781, 0.17716353,
       0.0935078 , 0.0935078 , 0.16981854, 0.09105477, 0.09554354,
       0.09608414, 0.11818173, 0.16064895, 0.10470676, 0.17337549,
       0.11102848, 0.23849154, 0.10009168, 0.73724398, 0.09175213,
       0.10959234, 0.51824117, 0.09240771, 0.09354202, 0.18075692,
       0.13811147, 0.16341322, 0.59784302, 0.24629693, 0.11204642,
       0.24313739, 0.09354202, 0.09351133, 0.15277287, 0.10088204,
       0.39010342, 0.23580673, 0.08683205, 0.16633409, 0.12222009,
       0.10576949, 0.2461523 , 0.11147928, 0.09371141, 0.1478758 ,
       0.23704799, 0.14414059, 0.14607386, 0.08573054, 0.15589923,
       0.09933694, 0.25828852, 0.12831338, 0.39416024, 0.15511053,
       0.13344645, 0.11657115, 0.10742249, 0.12026908, 0.11633002,
       0.38581938, 0.1863885 , 0.08884035, 0.7036177 , 0.16153227,
       0.11028811, 0.13320829, 0.14002428, 0.09554354, 0.2801509 ,
       0.35884188, 0.19006238, 0.25584984, 0.43758283, 0.19507605,
       0.13090262, 0.0947813 , 0.26425321, 0.12113917, 0.88202063,
       0.11003613, 0.16650718, 0.08082203, 0.10245747, 0.23117033,
       0.12740633, 0.11396902, 0.10622517, 0.09510918, 0.10003399,
       0.09386607, 0.09351133, 0.80519721, 0.15704927, 0.22669395,
       0.17584282, 0.14428583, 0.10280593, 0.21367792, 0.38643858,
       0.79199258, 0.09232858, 0.10254258, 0.13306672, 0.10212085,
       0.2055993 , 0.09775865, 0.10058293, 0.09288065, 0.10254258,
       0.09511999, 0.09999043, 0.10178882, 0.09332511, 0.14612735,
       0.10452481, 0.21673598, 0.102209  , 0.17119023, 0.17713893,
       0.26282252, 0.17330057, 0.10200843, 0.10398417, 0.47194529,
       0.10146091, 0.10219055, 0.17494336, 0.14856327, 0.43023431,
       0.23852498, 0.10152008, 0.09084865, 0.18460613, 0.13904112,
       0.08657402, 0.10705232, 0.18789268, 0.0848318 , 0.08798026,
       0.11488025, 0.09511049, 0.10581254, 0.11866745, 0.12464197,
       0.09504054, 0.12258838, 0.14906147, 0.22060406, 0.0827236 ,
       0.12650126, 0.099001  , 0.10443276, 0.09572568, 0.09101364,
       0.09232858, 0.10942692, 0.10918532, 0.16179991, 0.11553329,
       0.14036429, 0.14956525, 0.10581254, 0.21556555, 0.15413089,
       0.11783064, 0.18250137, 0.08795121, 0.13337306, 0.12465027,
       0.16217682, 0.09353017, 0.08129644, 0.10074767, 0.09384256,
       0.12291733, 0.18227074, 0.08482121, 0.18181734, 0.1459068 ,
       0.09909186, 0.09406762, 0.11818813, 0.22790821, 0.09148018,
       0.10959234, 0.08805329, 0.17953742, 0.09101364, 0.14157678,
       0.16355359, 0.12472405, 0.2381354 , 0.10742249, 0.12063255,
       0.22150522, 0.13103768, 0.09425292, 0.13183748, 0.13523068,
       0.10996116, 0.17713423, 0.11948685, 0.207283  , 0.10890239,
       0.7338826 , 0.70608301, 0.10583065, 0.54160232, 0.15855411,
       0.37239705, 0.12391952, 0.51619801, 0.0858071 , 0.10140541,
       0.11435922, 0.14298445, 0.09390961, 0.08865302, 0.09092382,
       0.11607883, 0.13208342, 0.23406621, 0.79373151, 0.19272673,
       0.11432036, 0.13609867, 0.18526222, 0.08682545, 0.09248405,
       0.08442641, 0.39192315, 0.09647636, 0.11049941, 0.09531445,
       0.08543193, 0.13936838, 0.10133275, 0.80699769, 0.30261302,
       0.08915309, 0.09717373, 0.11247946, 0.34201788, 0.08340171,
       0.43097261, 0.10119124, 0.12106452, 0.08543193, 0.12527851,
       0.32960618, 0.11336155, 0.09961853, 0.16182129, 0.1305016 ,
       0.34201198, 0.09288065, 0.10746194, 0.13057884, 0.10905959,
       0.08645688, 0.19616891, 0.10429608, 0.17893561, 0.13828801,
       0.09970452, 0.14181325, 0.09384256, 0.15539657, 0.12872781,
       0.09679027, 0.13027699, 0.66154175, 0.19913279, 0.08795121,
       0.70942382])

In [86]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
cm = confusion_matrix(y_test,y_pred)
precision = round(precision_score(y_test,y_pred, average="macro")*100,2)
acc_nb = round(accuracy_score(y_test,y_pred)*100,2)
recall = round(recall_score(y_test,y_pred, average="macro")*100,2)
f1score = round(f1_score(y_test, y_pred, average="macro")*100,2)
print('Konfusi Matrix\n',cm)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(f1score))
print('accuracy: {}'.format(acc_nb))

Konfusi Matrix
 [[226  12]
 [ 44   4]]
precision: 54.35
recall: 51.65
fscore: 50.74
accuracy: 80.42

In [87]:
X_test.dtypes

sex                float64
Age                float64
Number_children    float64
education_level    float64
total_members      float64
incoming_salary    float64
dtype: object

In [88]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [89]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
#Try running from k=1 through 30 and record testing accuracy
k_range = range(1,31)
scores = {}
scores_list = []
for k in k_range:
        # install model
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train,y_train)
        # save model
        filenameKNN = '/content/drive/MyDrive/DATA MINING/TUGAS/model/modelKNN'+str(k)+'.pkl'
        joblib.dump(knn,filenameKNN)
        y_pred=knn.predict(X_test)
        scores[k] = accuracy_score(y_test,y_pred)
        scores_list.append(accuracy_score(y_test,y_pred))
scores

{1: 0.7342657342657343,
 2: 0.8181818181818182,
 3: 0.7762237762237763,
 4: 0.8286713286713286,
 5: 0.8181818181818182,
 6: 0.8321678321678322,
 7: 0.8286713286713286,
 8: 0.8321678321678322,
 9: 0.8286713286713286,
 10: 0.8321678321678322,
 11: 0.8286713286713286,
 12: 0.8321678321678322,
 13: 0.8286713286713286,
 14: 0.8321678321678322,
 15: 0.8321678321678322,
 16: 0.8321678321678322,
 17: 0.8321678321678322,
 18: 0.8321678321678322,
 19: 0.8321678321678322,
 20: 0.8321678321678322,
 21: 0.8321678321678322,
 22: 0.8321678321678322,
 23: 0.8321678321678322,
 24: 0.8321678321678322,
 25: 0.8321678321678322,
 26: 0.8321678321678322,
 27: 0.8321678321678322,
 28: 0.8321678321678322,
 29: 0.8321678321678322,
 30: 0.8321678321678322}

In [90]:
scores_list.index(max(scores_list))+1 , max(scores_list)

(6, 0.8321678321678322)

In [91]:
from sklearn.cluster import KMeans

# #Try running from n=1 through 30 and record testing accuracy
n_range = range(1,31)
akurasi = {}
akurasi_score = []
for k in n_range:
        # install model
        kmeans = KMeans(n_clusters=k,random_state=0)
        kmeans.fit(X_train,y_train)
        # save model
        filenameKMeans = '/content/drive/MyDrive/DATA MINING/TUGAS/model/modelKmeans'+str(k)+'.pkl'
        joblib.dump(kmeans,filenameKMeans)
        y_pred=kmeans.predict(X_test)
        akurasi[k] = accuracy_score(y_test,y_pred)
        akurasi_score.append(accuracy_score(y_test,y_pred))
akurasi_score

[0.8321678321678322,
 0.3146853146853147,
 0.1993006993006993,
 0.17482517482517482,
 0.1048951048951049,
 0.11888111888111888,
 0.3321678321678322,
 0.12237762237762238,
 0.07342657342657342,
 0.1993006993006993,
 0.21678321678321677,
 0.16783216783216784,
 0.13636363636363635,
 0.06993006993006994,
 0.13986013986013987,
 0.04895104895104895,
 0.06293706293706294,
 0.06643356643356643,
 0.04195804195804196,
 0.04895104895104895,
 0.0979020979020979,
 0.03146853146853147,
 0.03146853146853147,
 0.038461538461538464,
 0.038461538461538464,
 0.06293706293706294,
 0.038461538461538464,
 0.017482517482517484,
 0.038461538461538464,
 0.07692307692307693]

In [92]:
akurasi_score.index(max(akurasi_score)) , max(akurasi_score)

(0, 0.8321678321678322)