#PROJECT PENAMBANGAN DATA


Langkah - langkah :
1. preprocessing drop data yang tidak diperlukan
2. split data sebelum di normalisasikan dan save csv data x.test
3. normalisasi data (min max) data yang telah di preprocessing drop data, save normalisasi (joblib)
4. split data yang telah di normalisasi

In [99]:
import pandas as pd
import numpy as np
data = pd.read_csv('https://raw.githubusercontent.com/AlifnurFathurrahmanPrasodjo/Project-Penambangan-Data/main/b_depressed.csv')
data.fillna(0,inplace=True)
data

,Survey_id,Ville_id,sex,Age,Married,Number_children,education_level,total_members,gained_asset,durable_asset,...,incoming_salary,incoming_own_farm,incoming_business,incoming_no_business,incoming_agricultural,farm_expenses,labor_primary,lasting_investment,no_lasting_investmen,depressed
0,926,91,1,28,1,4,10,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1,747,57,1,23,1,3,8,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,1
2,1190,115,1,22,1,3,9,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
3,1065,97,1,27,1,2,10,4,52667108,19698904,...,0,1,0,1,22288055,18751329,0,7781123,69219765.0,0
4,806,42,0,59,0,4,10,6,82606287,17352654,...,1,0,0,0,53384566,20731006,1,20100562,43419447.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,255,22,1,25,1,1,7,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1425,547,69,1,28,1,4,10,6,15711078,24023054,...,0,1,0,0,23022095,1021536,0,1823477,47384361.0,0
1426,893,184,1,66,0,0,1,1,42440731,22861940,...,0,1,0,0,12545373,10454478,0,46444572,10454478.0,1
1427,363,75,1,51,1,1,12,5,28912201,22861940,...,0,0,0,0,30028818,31363432,0,28411718,28292707.0,0
1428,231,12,1,33,0,4,8,5,81678391,22861940,...,0,1,0,1,20019212,16682677,0,69642126,13012488.0,0

In [100]:
fd1 = data.drop(data.columns[0:2],axis=1)

fd2 = fd1.drop(fd1.columns[2],axis=1)
#fd3 = fd2.drop(fd2.columns[18],axis=1)

fd3 = fd2.drop(fd2.columns[5:10],axis=1)

fd4 = fd3.drop(fd3.columns[6:14],axis=1)



fd4

,sex,Age,Number_children,education_level,total_members,incoming_salary,depressed
0,1,28,4,10,5,0,0
1,1,23,3,8,5,0,1
2,1,22,3,9,5,0,0
3,1,27,2,10,4,0,0
4,0,59,4,10,6,1,0
...,...,...,...,...,...,...,...
1424,1,25,1,7,5,0,0
1425,1,28,4,10,6,0,0
1426,1,66,0,1,1,0,1
1427,1,51,1,12,5,0,0
1428,1,33,4,8,5,0,0

In [101]:
fd4.dropna(how="any")

fd4

,sex,Age,Number_children,education_level,total_members,incoming_salary,depressed
0,1,28,4,10,5,0,0
1,1,23,3,8,5,0,1
2,1,22,3,9,5,0,0
3,1,27,2,10,4,0,0
4,0,59,4,10,6,1,0
...,...,...,...,...,...,...,...
1424,1,25,1,7,5,0,0
1425,1,28,4,10,6,0,0
1426,1,66,0,1,1,0,1
1427,1,51,1,12,5,0,0
1428,1,33,4,8,5,0,0

In [102]:
y = fd4['depressed'].values
x = fd4.drop(fd4.columns[6],axis=1)
x

,sex,Age,Number_children,education_level,total_members,incoming_salary
0,1,28,4,10,5,0
1,1,23,3,8,5,0
2,1,22,3,9,5,0
3,1,27,2,10,4,0
4,0,59,4,10,6,1
...,...,...,...,...,...,...
1424,1,25,1,7,5,0
1425,1,28,4,10,6,0
1426,1,66,0,1,1,0
1427,1,51,1,12,5,0
1428,1,33,4,8,5,0

In [103]:
#x.nlargest(3, "Age")
# x.nlargest(3, "Number_children")
#x.nlargest(3, "education_level")
#x.nlargest(3, "total_members")
# x.nlargest(3, "incoming_salary")

#x.nsmallest(3, "Age")
x.nsmallest(3, "Number_children")
#x.nsmallest(3, "education_level")
#x.nsmallest(3, "total_members")
# x.nsmallest(3, "incoming_salary")

    sex  Age  Number_children  education_level  total_members  incoming_salary
10    1   84                0                1              5                0
14    1   56                0               12              2                0
20    1   40                0                7              5                0

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=1)
X_train.shape + X_test.shape

(1143, 6, 286, 6)

In [105]:
X_test

,sex,Age,Number_children,education_level,total_members,incoming_salary
951,1,27,1,11,5,0
1059,1,21,3,10,5,0
1268,0,53,0,14,5,0
236,1,22,4,8,6,1
942,1,30,3,10,5,0
...,...,...,...,...,...,...
1311,1,32,6,10,8,0
1284,0,47,0,1,5,0
602,1,56,0,7,2,0
1319,1,25,2,9,4,0
516,1,61,0,1,5,0

In [106]:
X_train.isna().sum()

sex                0
Age                0
Number_children    0
education_level    0
total_members      0
incoming_salary    0
dtype: int64

In [107]:
from pathlib import Path  
filepath = Path('/content/drive/MyDrive/DATA MINING/TUGAS/model/data_depresi.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
x.to_csv(filepath)

In [108]:
x.isna().sum()

sex                0
Age                0
Number_children    0
education_level    0
total_members      0
incoming_salary    0
dtype: int64

In [109]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)
y

array([0, 1, 0, ..., 1, 0, 0])

In [110]:
y_class = data['depressed']
y = y_class.values.tolist()
print(y)

[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

In [111]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [112]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled = scaler.fit_transform(x)
nama_fitur = x.columns.copy()
scaled_fitur = pd.DataFrame(scaled,columns=nama_fitur)
scaled_fitur

,sex,Age,Number_children,education_level,total_members,incoming_salary
0,1.0,0.148649,0.363636,0.500000,0.363636,0.0
1,1.0,0.081081,0.272727,0.388889,0.363636,0.0
2,1.0,0.067568,0.272727,0.444444,0.363636,0.0
3,1.0,0.135135,0.181818,0.500000,0.272727,0.0
4,0.0,0.567568,0.363636,0.500000,0.454545,1.0
...,...,...,...,...,...,...
1424,1.0,0.108108,0.090909,0.333333,0.363636,0.0
1425,1.0,0.148649,0.363636,0.500000,0.454545,0.0
1426,1.0,0.662162,0.000000,0.000000,0.000000,0.0
1427,1.0,0.459459,0.090909,0.611111,0.363636,0.0
1428,1.0,0.216216,0.363636,0.388889,0.363636,0.0

In [113]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(scaled_fitur, y, test_size=0.2, random_state=1)
X_train.shape + X_test.shape

(1143, 6, 286, 6)

In [114]:
import joblib
filename = '/content/drive/MyDrive/DATA MINING/TUGAS/model/norm.sav'
joblib.dump(scaler, filename)

['/content/drive/MyDrive/DATA MINING/TUGAS/model/norm.sav']

In [115]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train,y_train)
probas = clf.predict_proba(X_test)[:,1]
y_pred = clf.predict(X_test)

y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [116]:
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
# from sklearn import metrics
# #Try running from k=1 through 30 and record testing accuracy
# k_range = range(1,31)
# scores = {}
# scores_list = []
# for k in k_range:
#         # install model
#         knn = KNeighborsClassifier(n_neighbors=k)
#         knn.fit(X_train,y_train)
      
#         filenameKNN = '/content/drive/MyDrive/DATA MINING/TUGAS/model/knnmodel'+str(k)+'.pkl'
#         joblib.dump(knn,filenameKNN)
#         y_pred=knn.predict(X_test)
#         scores[k] = accuracy_score(y_test,y_pred)
#         scores_list.append(accuracy_score(y_test,y_pred))
# scores

In [117]:
#X_test

In [118]:
# import joblib
# filenameNB = '/content/drive/MyDrive/DATA MINING/TUGAS/model/modelNB.pkl'
# joblib.dump(clf,filenameNB)

In [119]:
#probas

In [120]:
# from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
# cm = confusion_matrix(y_test,y_pred)
# precision = round(precision_score(y_test,y_pred, average="macro")*100,2)
# acc_nb = round(accuracy_score(y_test,y_pred)*100,2)
# recall = round(recall_score(y_test,y_pred, average="macro")*100,2)
# f1score = round(f1_score(y_test, y_pred, average="macro")*100,2)
# print('Konfusi Matrix\n',cm)
# print('precision: {}'.format(precision))
# print('recall: {}'.format(recall))
# print('fscore: {}'.format(f1score))
# print('accuracy: {}'.format(acc_nb))

In [121]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
#Try running from k=1 through 30 and record testing accuracy
k_range = range(1,31)
scores = {}
scores_list = []
for k in k_range:
        # install model
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train,y_train)
        # save model
        filenameKNN = '/content/drive/MyDrive/DATA MINING/TUGAS/model/modelKNN'+str(k)+'.pkl'
        joblib.dump(knn,filenameKNN)
        y_pred=knn.predict(X_test)
        scores[k] = accuracy_score(y_test,y_pred)
        scores_list.append(accuracy_score(y_test,y_pred))
scores

{1: 0.7342657342657343,
 2: 0.8181818181818182,
 3: 0.7762237762237763,
 4: 0.8286713286713286,
 5: 0.8181818181818182,
 6: 0.8321678321678322,
 7: 0.8286713286713286,
 8: 0.8321678321678322,
 9: 0.8286713286713286,
 10: 0.8321678321678322,
 11: 0.8286713286713286,
 12: 0.8321678321678322,
 13: 0.8286713286713286,
 14: 0.8321678321678322,
 15: 0.8321678321678322,
 16: 0.8321678321678322,
 17: 0.8321678321678322,
 18: 0.8321678321678322,
 19: 0.8321678321678322,
 20: 0.8321678321678322,
 21: 0.8321678321678322,
 22: 0.8321678321678322,
 23: 0.8321678321678322,
 24: 0.8321678321678322,
 25: 0.8321678321678322,
 26: 0.8321678321678322,
 27: 0.8321678321678322,
 28: 0.8321678321678322,
 29: 0.8321678321678322,
 30: 0.8321678321678322}

In [122]:
scores_list.index(max(scores_list))+1 , max(scores_list)

(6, 0.8321678321678322)

In [123]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [124]:
#evaluasi model
knn = KNeighborsClassifier(n_neighbors=scores_list.index(max(scores_list))+1)
knn.fit(X_train,y_train)
y_pred_knn =knn.predict(X_test)
# y_pred_knn
cm = confusion_matrix(y_test,y_pred_knn)
precision = round(precision_score(y_test,y_pred_knn, average="macro")*100,2)
acc = round(accuracy_score(y_test,y_pred_knn)*100,2)
recall = round(recall_score(y_test,y_pred_knn, average="macro")*100,2)
f1score = round(f1_score(y_test, y_pred_knn, average="macro")*100,2)
print('Konfusi Matrix\n',cm)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(f1score))
print('accuracy: {}'.format(acc))

Konfusi Matrix
 [[238   0]
 [ 48   0]]
precision: 41.61
recall: 50.0
fscore: 45.42
accuracy: 83.22

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [125]:
from sklearn.cluster import KMeans

# #Try running from n=1 through 30 and record testing accuracy
n_range = range(1,31)
akurasi = {}
akurasi_score = []
for k in n_range:
        # install model
        kmeans = KMeans(n_clusters=k,random_state=0)
        kmeans.fit(X_train,y_train)
        # save model
        filenameKMeans = '/content/drive/MyDrive/DATA MINING/TUGAS/model/modelKmeans'+str(k)+'.pkl'
        joblib.dump(kmeans,filenameKMeans)
        y_pred=kmeans.predict(X_test)
        akurasi[k] = accuracy_score(y_test,y_pred)
        akurasi_score.append(accuracy_score(y_test,y_pred))
akurasi_score

[0.8321678321678322,
 0.3146853146853147,
 0.1993006993006993,
 0.17482517482517482,
 0.1048951048951049,
 0.11888111888111888,
 0.3321678321678322,
 0.12237762237762238,
 0.07342657342657342,
 0.1993006993006993,
 0.21678321678321677,
 0.16783216783216784,
 0.13636363636363635,
 0.06993006993006994,
 0.13986013986013987,
 0.04895104895104895,
 0.06293706293706294,
 0.06643356643356643,
 0.04195804195804196,
 0.04895104895104895,
 0.0979020979020979,
 0.03146853146853147,
 0.03146853146853147,
 0.038461538461538464,
 0.038461538461538464,
 0.06293706293706294,
 0.038461538461538464,
 0.017482517482517484,
 0.038461538461538464,
 0.07692307692307693]

In [126]:
akurasi_score.index(max(akurasi_score)) , max(akurasi_score)

(0, 0.8321678321678322)

In [127]:
KMeans = KNeighborsClassifier(n_neighbors=akurasi_score.index(max(akurasi_score))+1)
KMeans.fit(X_train,y_train)
y_pred_KMeans =KMeans.predict(X_test)
# y_pred_KMeans
cm = confusion_matrix(y_test,y_pred_KMeans)
precision = round(precision_score(y_test,y_pred_KMeans, average="macro")*100,2)
acc = round(accuracy_score(y_test,y_pred_KMeans)*100,2)
recall = round(recall_score(y_test,y_pred_KMeans, average="macro")*100,2)
f1score = round(f1_score(y_test, y_pred_KMeans, average="macro")*100,2)
print('Konfusi Matrix\n',cm)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(f1score))
print('accuracy: {}'.format(acc))

Konfusi Matrix
 [[206  32]
 [ 44   4]]
precision: 46.76
recall: 47.44
fscore: 46.98
accuracy: 73.43